module.exports = {
    "justification-for-establishing-the-centre": { data: "justification", nav: "about" },
    "vision": { data: "vision", nav: "about" },
    "mission": { data: "mission", nav: "about" },
    "objectives": { data: "objectives", nav: "about" },
    "education": { data: "education", nav: "programmes" },
    "teaching": { data: "teaching", nav: "programmes" },
    "learning-activities": { data: "learning-activities", nav: "programmes" },
    "skills-gap": { data: "skills-gap", nav: "programmes" },
    "innovations-in-pedagogy": { data: "innovations-in-pedagogy", nav: "programmes" },
    "degree-programmes": { data: "degree-programmes", nav: "education" },
    "online-courses": { data: "online-courses", nav: "programmes" },
    "lecture-rooms": { data: "lecture-rooms", nav: "programmes" },
    "research-plan": { data: "research-plan", nav: "research" },
    "industrial-partnerships": { data: "industrial-partnerships", nav: "research" },
    "academic-partnerships": { data: "academic-partnerships", nav: "research" },
    "retention-and-support": { data: "retention-support", nav: "management" },
    "student-recruitment": { data: "student-recruitment", nav: "management" },
    "staff-development": { data: "staff", nav: "management" },
    "centre-operations": { data: "centre-operations", nav: "management" },
    "implementation-timeline": { data: "implementation-timeline", nav: "management" },
    "industrial-advisory-boards": { data: "industrial-advisory-boards", nav: "management" }
};